### PR TITLE
Custom federation mechanism for Ivits

### PR DESCRIPTION
**Pull request by coyotte508**
Do #34

### CODE REVIEW

**Comment by coyotte508** [comment]
Because `player.data.federations` can include the terraforming federation (on last research tile of terraforming).

The ivits need to know the real numbers of federations built, because their federation cost depends on that. If I don't use federationCount, and the ivits get to the last tile of terraforming, they would need to use 14 VP instead of 7 for their first federation...

**Comment by rzulian** [comment]
But the rule states "where X is the number of federation tokens you own plus one", so if they get the terraforming one, they have to pay 7 more.

**Comment by rzulian** [comment]
Right! What if we align federations tile with Adv tech and std tech?  ` federationTiles: Array<{ tile: FederationTile, green: boolean, value: number}> = []; `

**Comment by rzulian** [comment]
I'll add this info to the #64

**Comment by coyotte508** [comment]
You can't put `value` in there, because there could be a case with two identical federation tiles, one used and one green.

But  Array<{ tile: FederationTile, green: boolean}> is good!

**Pull request merged**
