### PR TITLE
fix Lantids on Lost planet

### PR DESCRIPTION
**Pull request by rzulian**

### CODE REVIEW

**Comment by coyotte508** [comment]
Lantids won't gain income from the planet they place near lost planet.

The fix is in the wrong place, it should be around line 401. (even without the income problem, I would still insist)

And there's the check on 416 which needs to be changed to add Lantids income.

A boolean variable `isLostPlanet` should probably be created like `const isNewLostPlanet = hex.planet === Planet.Lost && !hex.isOccupied()` and used in the subsequent tests.

**Comment by rzulian** [comment]
That's not the bug were are talking about. The bug is that Lantids can add a mine to a LostPlanet, but they need to "consume" a mine. Line 401 was wrong.

**Comment by coyotte508** [comment]
There were two bugs:

- Lantids don't consume a mine when they place on lost planet
- Lantids don't get income when they place on lost planet

The PR only fixes bug 1. I want to fix bug 1 & 2.

Also a test should probably be added because a regression can easily happen with this kind of edge case.

**Comment by rzulian** [comment]
OK. What if I change `engine.ts`: 1435 to a new function for the lost planet, instead of using the `build` to manage the lostPlanet?

**Comment by coyotte508** [comment]
Well ok but you have then to split out two part of the function into new functions:

```
    this.payCosts(cost, Command.Build);
    const wasOccupied = this.data.occupied.includes(hex);
    // excluding Gaiaformers as occupied
    if (building !== Building.GaiaFormer) {
      if (!wasOccupied) {
        this.data.occupied.push(hex);
        // Clear federation cache on new building
        this.federationCache = null;
      }


      if (this.federationCache) {
        assert(wasOccupied, "logic error");

        if (this.buildingValue(hex, {federation: true}) === this.buildingValue(hex, {federation: true, building})) {
          // No need to clear federation cache, when the building value remains the same
        } else if (!hex.belongsToFederationOf(this.player)) {
          this.federationCache = null;
        } else if (this.faction === Faction.Ivits) {
          // Ivits can build a federation with existing federation buildings
          this.federationCache = null;
        }
      }
    }
```

(though all the federation cache stuff can be simplified to `this.federationCache = null`)

and

```
    // Add to nearby federation
    if (building !== Building.GaiaFormer && !hex.belongsToFederationOf(this.player)) {
      const group: GaiaHex[] = this.buildingGroup(hex, map);
      const hasFederation = map.grid.neighbours(hex).some(hx => hx.belongsToFederationOf(this.player));

      if (hasFederation) {
        for (const h of group) {
          h.addToFederationOf(this.player);
        }
      }
    }

    // get triggered income for new building
    this.receiveBuildingTriggerIncome(building, hex.data.planet, isAdditionalMine);

//    // get triggerd terffaorming step income for new building
//    if (stepsReq) {
//      this.receiveTerraformingStepTriggerIncome(stepsReq);
//    }

    // Faction-specific code on building
    this.emit(`build-${building}`, hex);
```

The change I suggested is basically adding one line of code, and modifying a few test conditions (it's even less additions than the current PR)

**Pull request merged**
